### ISSUE TITLE
Running the interactive application despite not having inserting the exact specified line

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/iguide-bulkhead#154]
Under the 'Adding the bulkhead annotation' section in this guide (https://openliberty.io/guides/bulkhead.html#adding-the-bulkhead-annotation) it is detailed that if a parameter for the `@Bulkhead` annotation is not specified the default value is 10.  When I tried to write `@Bulkhead` as opposed to `@Bulkhead(50)` the application will not run.  

I am not sure whether this is in the scope of the interactive guides but it would be interesting if I would still be able to run the application.  Perhaps the guide would run but not let me move on to the next step (or that step would not be marked as complete).  Some room to experiment would help gain a deeper understanding of the tool.

**Comment by dmorgant** [comment]
Hello Kathryn.   Thank you for writing to us an Happy New Year!

So on the 'Adding the bulkhead annotation' section, we must enforce that the annotation entered into the editor at this point is `@Bulkhead(50)` exactly so that the second step in this section makes sense.  If I enter only `@Bulkhead` at this point, the editor shows an error like the following and the step is **not** marked complete:

![image](https://user-images.githubusercontent.com/29490139/50599358-dd6a2c80-0e7b-11e9-8d84-c9edc20b7bd3.png)

**Comment by kathrynkodama** [comment]
Hello,

I see the same behaviour as you have detailed above.  In order to move on to the next step I am forced to enter `@Bulkhead(50)` exactly.  

I simply meant because there is a discussion in this section about the default value for `@Bulkhead`, it would be interesting if there was a way to incorporate this into this step of the interactive guide.  Perhaps allow for the application to run but maybe not allow the user to move on to the next step.  Initially when I tried to change `@Bulkhead(50)` to `@Bulkhead` and I could no longer run the application I thought perhaps I had made some sort of syntax error.   I do like the interactive section of the guide and found it very useful!

**Comment by mbroz2** [comment]
@kathrynkodama if you did make it to the playground, did it allow you to do what you wanted to (other than the bug where @Bulkhead annotation without a value did not properly use the default)?

I think the main problem here is that it was not clear that other valid code could not be entered during this step, and the error that gets displayed further doesn't clarify this either.  Also, if the user does want to experiment with different values at this point, we currently do not let them know about the playground step that they could skip forward to.  I think this could be addressed in one of two ways:
1) make the step like the playground.  
2) clarify that in this step only the code snippet in the instruction is valid, but the playground step at the end will allow for other values.

For now, I think we should take the approach in step 2 as doing step 1 would necessitate more considerations (do we need to make all the steps in this guide interactive? what about the other guides?  do we use the playground interaction or the step interaction since they're different?)

@kathrynkodama if we had provided a message like "You'll be able to experiment with your own values in the playground step." which linked to the playground, do you think that would have been helpful and sufficient?

**Comment by kathrynkodama** [comment]
@mbroz2 I found the interactive playground very useful and I was able to experiment with everything I wanted to.  I think providing the proposed message would be very helpful because I was unaware of the interactive playground step until I reached the end of the guide.

**Comment by dmorgant** [comment]
@kathrynkodama  We have completed making changes to the guide based on this issue you opened.  You will be able to view the changes once they have made it to master and have been published on the web site.
